using Robocode;

namespace Santom
{
	/// <summary>
	/// Helper class, storing data about a bullet. 
	/// version: 1.0
	/// author: Tomas Sandnes - santom@nith.no
	/// </summary>
	public class BulletData
	{

		// P R O P E R T I E S
		// -------------------

		public Bullet Stats { get; set; }  // The original Bullet object, generated by SetFireBullet() or the like.
		public Point2D Origin { get; set; }  // Bullet start position, in battlefield x y coordinates (own position at time of firing).
		public Point2D Destination { get; set; }  // Bullet target position, in battlefield x y coordinates (NOT the same as enemy position if we use targeting systems).


		// P U B L I C   M E T H O D S 
		// ---------------------------

		public BulletData(Bullet bulletStats,
						  Point2D bulletOrigin, 
						  Point2D bulletDestination)
		{
			Stats = bulletStats;
			Origin = bulletOrigin;
			Destination = bulletDestination;
		}
	}
}